#!/bin/sh

if [ ! -p /dev/raid_monitor ]; then
    /usr/bin/mkfifo /dev/raid_monitor
fi

# when using syslogd and klogd
if [ -f /sbin/syslogd ]; then

	#rewrite previous configuration

	perl -pi -e 's#kern.*/dev/raid_monitor##g' /etc/syslog.conf 
	echo ""
	echo "kern.*		|/dev/raid_monitor" >> /etc/syslog.conf

	/etc/init.d/sysklogd	restart
	/etc/init.d/klogd		restart



	if [ -e "/etc/default/klogd" ] ; then
		perl -pi -e 's/^KLOGD.*/KLOGD="-x"/' /etc/default/klogd
	else
		echo '#
# top configuration file for klogd
#

#
# Full documentation of possible arguments are found in the manpage
# klogd(8).
#

#
# Use KLOGD=-k /boot/System.map-2.6.24.7-storiq64-smp to specify System.map
# -c 4 to alter the kernel console log level (deprecated)
#   use sysctl instead
#
KLOGD="-x"' > /etc/default/klogd

	fi
# when using rsyslog
elif [  -f /usr/sbin/rsyslogd ]; then
	perl -pi -e 's#kern.*/dev/raid_monitor##g' /etc/rsyslog.conf 
	echo ""
	echo "kern.*		|/dev/raid_monitor" >> /etc/rsyslog.conf

	/etc/init.d/rsyslog	restart
	
fi
	

rm -f /etc/rc*.d/*raid_monitor

systemctl daemon-reload

systemctl start raid_control
systemctl enable raid_monitor
systemctl start raid_monitor

